import type { NextPage, InferGetServerSidePropsType} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {ghostClient} from '../ghostCMSClient'
import { MenuBar } from '../components/MenuBar'

type Props = InferGetServerSidePropsType<typeof getStaticProps>;
const Home: NextPage<Props> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuBar/>
      {posts.map((post, idx) => <p key={idx}>{post.title}</p>)}
    </div>
  )
}

export const getStaticProps = async () => {
  const posts = await ghostClient.posts.browse();
  const pages = await ghostClient.pages.browse();
  return {
    props: {
      posts,
      pages
    }
  }
}

export default Home
